sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
after_script:
  - cat ./__tests__/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
